# Lug'atlar
[[translations]]
en = "Infiltrating"
uz = "Kirish"
description = ""
pronunciation_uz = ""

[[translations]]
en = "Debug"
uz = "Debag"
description = ""
pronunciation_uz = ""

[[translations]]
en = "Debugging"
uz = "Debaglash"
description = ""
pronunciation_uz = ""

[[translations]]
en = "Sensor"
uz = "Sensor"
description = ""
pronunciation_uz = "sensr"

[[translations]]
en = "Multithread"
uz = "Ko'p oqimli"
description = "Ko'p oqimli ishlov berish jarayoni haqida atama."
pronunciation_uz = ""

[[translations]]
en = "Single thread"
uz = "Bir oqimli"
description = "Bitta oqim bilan ishlaydigan jarayon."
pronunciation_uz = ""

[[translations]]
en = "Concurrency"
uz = "Parallel ishlash"
description = "Bir nechta vazifalarni bir vaqtda boshqarish."
pronunciation_uz = ""

[[translations]]
en = "parse"
uz = "parse"
description = ""
pronunciation_uz = "pars"

[[translations]]
en = "parsing"
uz = "parsing"
description = ""
pronunciation_uz = "parsing"

[[translations]]
en = "IT"
uz = "AyTi"
description = ""
pronunciation_uz = "ayti"

[[translations]]
en = "Authentication"
uz = "Tasdiqlash"
description = ""
pronunciation_uz = ""

[[translations]]
en = "Authorization"
uz = "Ruxsat"
description = "tasdiqlash deb tarjima chiqyapti lekin ruxsat ma'nosida keldi ko'pincha meni tajribamda"
pronunciation_uz = ""

[[translations]]
en = "Option"
uz = "Tanlov"
description = ""
pronunciation_uz = ""

[[translations]]
en = "Framework"
uz = "Freymvork"
description = ""
pronunciation_uz = "Freymvo'rk"

[[translations]]
en = "Folder"
uz = "Jild"
description = ""
pronunciation_uz = ""

[[translations]]
en = "Directory"
uz = "Katalog"
description = ""
pronunciation_uz = ""

[[translations]]
en = "Branch"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "account"
uz = "hisob"
description = ""
pronunciation_uz = ""

[[translations]]
en = "username"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "Advanced"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "layout"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "release"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "Category"
uz = "Tasnif"
description = ""
pronunciation_uz = ""

[[translations]]
en = "Original"
uz = "Asl nusxa"
description = ""
pronunciation_uz = ""

[[translations]]
en = "Fuzzy"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "Progress"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "Error"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "Reviewer"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "Review"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "workflow"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "scrape"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "Repository"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "Feedback"
uz = "Sharh"
description = ""
pronunciation_uz = ""

[[translations]]
en = "Firmware"
uz = ""
description = ""
pronunciation_uz = ""

[[translations]]
en = "charge"
uz = "quvvat"
description = ""
pronunciation_uz = ""
